version: "3.8"
services:
   web:
      image: krpetrov/apache-php
      ports:
         - 8080:80
      volumes:
         - "${PROJECT_ROOT}:/var/www/html:ro"
      networks:
         - app-network
   db:	
      image: krpetrov/img-db      
      networks:
         - app-network
      environment:
         MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
   app-network:
